name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *' # run daily at midnight
  workflow_dispatch: # allow manual trigger

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --json > audit-results.json
        continue-on-error: true

      - name: Check vulnerabilities
        run: |
          if grep -q '"vulnerabilities":{' audit-results.json; then
            echo "Vulnerabilities found!"
            exit 1
          else
            echo "No vulnerabilities found."
          fi

      - name: Create issue if vulnerabilities found
        if: failure() # only runs if previous step fails
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Security vulnerabilities detected in dependencies"
          content-filepath: ./audit-results.json
          labels: security
